version: 0.1
services:
  packtrace-web:
    image: YOUR_DOCKERHUB_USERNAME/pack-trace:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
        protocol: TCP
        expose: true
    env:
      - name: NEXT_PUBLIC_NETWORK
        value: "{{.NEXT_PUBLIC_NETWORK}}"
        default: "testnet"
      - name: HEDERA_TOPIC_ID
        value: "{{.HEDERA_TOPIC_ID}}"
      - name: HEDERA_OPERATOR_ACCOUNT_ID
        value: "{{.HEDERA_OPERATOR_ACCOUNT_ID}}"
      - name: HEDERA_OPERATOR_DER_PRIVATE_KEY
        value: "{{.HEDERA_OPERATOR_DER_PRIVATE_KEY}}"
      - name: NEXT_PUBLIC_SUPABASE_URL
        value: "{{.NEXT_PUBLIC_SUPABASE_URL}}"
      - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "{{.NEXT_PUBLIC_SUPABASE_ANON_KEY}}"
      - name: SUPABASE_SERVICE_ROLE_KEY
        value: "{{.SUPABASE_SERVICE_ROLE_KEY}}"
      - name: SUPOS_BRIDGE_ENABLED
        value: "{{.SUPOS_BRIDGE_ENABLED}}"
        default: "false"
      - name: SUPOS_MQTT_URL
        value: "{{.SUPOS_MQTT_URL}}"
        default: "mqtt://localhost:1883"
      - name: SUPOS_MQTT_USERNAME
        value: "{{.SUPOS_MQTT_USERNAME}}"
        default: ""
      - name: SUPOS_MQTT_PASSWORD
        value: "{{.SUPOS_MQTT_PASSWORD}}"
        default: ""
      - name: SUPOS_BRIDGE_QOS
        value: "1"
      - name: SUPOS_CLIENT_ID
        value: "{{.SUPOS_CLIENT_ID}}"
        default: ""
      - name: SUPOS_BRIDGE_CONCURRENCY
        value: "8"
      - name: SUPOS_BRIDGE_MAX_ATTEMPTS
        value: "8"
      - name: SUPOS_BRIDGE_BASE_DELAY_MS
        value: "1000"
    resourceUsage:
      idle:
        cpu: 500
        memory: 1024
